Enhance release workflow, set to testpypi to check

diff --git a/.github/workflows/deploypypi.yml b/.github/workflows/deploypypi.yml
--- a/.github/workflows/deploypypi.yml
+++ b/.github/workflows/deploypypi.yml
@@ -53,5 +53,44 @@ jobs:
         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
       run: |
+        python -m pip install --upgrade pip
         python setup.py sdist bdist_wheel
-        twine upload dist/*
+        twine upload --repository testpypi dist/*
+
+  check-released:
+    runs-on: ubuntu-latest
+    needs: [publish]
+    timeout-minutes: 10
+    steps:
+    - name: Set up Python 3.12
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Install and import the uploaded package
+      run: |
+        python -m pip install --upgrade pip
+        while true; do
+          log=$(
+            python -m pip install \
+              --index-url https://test.pypi.org/simple/ \
+              --extra-index-url https://pypi.org/simple/ \
+              "substrate-interface==${GITHUB_REF#refs/tags/v}"
+          )
+          status=$?
+          if [ "$status" = 0 ]; then
+            echo "Installed successfully."
+            break
+          elif grep -q 'Could not find a version' <<<"$log"; then
+            echo "Waiting for release to propagate to the index..."
+            sleep 5
+          else
+            echo '::error::Unexpected output from "pip install", release seems to have failed.'
+            exit 1
+          fi
+        done
+
+        if ! python -c 'import substrateinterface'; then
+          echo '::error::Unable to import the installed package!'
+          exit 2
+        fi
